spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sqlTest
    username: postgres
    password: postgres
    
  web:
    cors:
      allowed-origins: "http://localhost:8081"
